import { serviceTrades, serviceStyles } from './serviceTemplateCatalog.ts';
import { serviceTemplateImages } from './serviceTemplateImages.ts';
export function serviceTemplateDocument(template, name) {
  const trade = serviceTrades.find(t => serviceStyles.some(s => `${t.id}-${s.id}` === template));
  if (!trade) return null;
  const style = serviceStyles.find(s => `${trade.id}-${s.id}` === template);
  const image = serviceTemplateImages[trade.id];
  const dark = style.id === 'commercial', background = dark ? '#121c2b' : '#ffffff', foreground = dark ? '#f8fafc' : '#172033';
  const tint = dark ? '#1e293b' : trade.tint, primary = dark ? '#93c5fd' : trade.primary;
  const run = text => ({ text, bold: false, italic: false, underline: false });
  const block = (id, type, title, copy, extra = {}) => ({ id, type, title, body: [run(copy)], image_id: '', alt: '', button: '', href: '', layout: style.layout, spacing: style.spacing, background, foreground, ...extra });
  const page = (id, title, blocks) => ({ id, slug: id, title, kind: 'page', visible: true, seo_title: `${title} | ${name}`.slice(0, 160), seo_description: `${trade.label} services for ${trade.audience}. Explore services and discuss your project with ${name}.`.slice(0, 320), category: '', blocks });
  const hero = block('hero', 'hero', trade.headline[serviceStyles.indexOf(style)], `Explore ${trade.label.toLowerCase()} services for ${trade.audience}. ${trade.detail}`, { image_id: image.id, alt: image.alt, layout: ['modern', 'commercial', 'booking'].includes(style.id) ? 'split' : style.layout, background: style.id === 'neighborhood' ? tint : background, button: style.id === 'booking' ? 'Request a visit' : 'Explore services', href: style.id === 'booking' ? '#visit-request' : '/services' });
  const services = block('service-overview', 'text', dark ? 'Service capabilities' : 'How we can help', trade.services.map(([title, copy]) => `${title}\n${copy}`).join('\n\n'), { background: tint });
  const process = block('project-process', 'text', 'A clear path from idea to next step', trade.process, { spacing: 'normal' });
  const approach = block('our-approach', 'text', 'Your property. Your priorities.', `Every property has its own needs. Start a conversation about your goals, preferences and the ${trade.label.toLowerCase()} work you have in mind.`, { background: tint });
  const area = block('service-area', 'text', 'Local service, shaped around you', 'Add the towns and neighborhoods you serve here. Confirm service availability and scheduling with your team before making a request.', { spacing: 'compact' });
  const planning = block('coordination', 'text', 'Built around your property requirements', 'Discuss access arrangements, scope, scheduling and site-specific requirements before work begins. Add your actual commercial capabilities and qualifications here.');
  const journal = block('project-journal', 'cta', 'A closer look at the work', 'Use your project journal to explain the challenge, approach and finished result. Add only your own authorized project photos and verified details.', { button: 'Explore the journal', href: '/projects', background: tint });
  const request = block('visit-request', 'booking', 'Request a visit', 'Share a preferred date and time. This is a request, not a confirmed appointment.', { background: tint });
  const details = block('request-details', 'text', 'What to include in your request', trade.detail, { spacing: 'compact' });
  const cta = block('get-started', 'cta', dark ? 'Discuss your next scope of work' : 'Let’s talk about your project', trade.detail, { button: 'Get in touch', href: '/contact', background: tint });
  const compositions = { modern: [hero, services, process, cta], neighborhood: [hero, approach, services, area, cta], showcase: [hero, process, services, journal, cta], commercial: [hero, services, planning, process, cta], booking: [hero, request, details, services, process] };
  const pages = [page('home', 'Home', compositions[style.id]), page('services', 'Services', [block('services-heading', 'hero', `${trade.label} services`, `Explore options for ${trade.audience}. Customize this list to match the work your business actually offers.`), ...trade.services.map(([title, copy], i) => block(`service-${i + 1}`, 'text', title, copy, { background: i % 2 === 0 ? tint : background, spacing: 'normal' })), block('services-contact', 'cta', 'Discuss the right scope', trade.detail, { button: 'Request information', href: '/contact' })]), page('about', 'About', [block('about-heading', 'hero', `Meet ${name}`, 'Introduce your team, your story and the way you work. This is sample copy to personalize before publication.'), block('about-approach', 'text', 'Care in the details', 'Describe your actual process, communication and project standards. Only include qualifications, licenses or guarantees your business can verify.'), block('about-area', 'text', 'Where we work', 'Replace this section with your real service area and availability.')]), page('contact', 'Contact', [block('contact-heading', 'hero', 'Start a conversation', trade.detail), block('contact-form', 'contact', 'Tell us how we can help', 'Send your details and a description of the work you have in mind.')]), page('guide', 'Planning guide', [block('guide-heading', 'hero', trade.tip, trade.advice), block('guide-questions', 'text', 'Questions for your provider', 'What is included in the scope? What preparation is needed? How will timing and any changes be confirmed?'), block('guide-contact', 'cta', 'Ready to discuss the details?', trade.detail, { button: 'Contact us', href: '/contact' })])];
  if (style.id === 'showcase') pages.push(page('projects', 'Project journal', [block('projects-heading', 'hero', 'Your work, in your own words', 'Sample project page — replace with a real project and authorized images before publication.'), block('project-story', 'text', 'The brief. The approach. The result.', 'Describe a real customer need, the work completed and the final result. Add project photos using the media library; do not invent customer endorsements.')]));
  return { schema_version: 1, name, tagline: `${trade.label} · Sample website — customize before publishing`, footer: 'Sample website. Replace with your business details, service area and contact information before publishing.', theme: { primary, background: style.id === 'neighborhood' ? tint : background, foreground, font: style.font, radius: style.radius }, categories: [], reusable: [], menu: pages.map(p => ({ label: p.title, slug: p.slug })), pages };
}