export const serviceTrades = [
  { id: 'cleaning', label: 'Cleaning', primary: '#0f766e', tint: '#ecfdf5', headline: ['A fresh start for every space', 'A cleaner home. More time for you.', 'Make room for a brighter space', 'Cleaning that works around your business', 'Your next clean starts here'], services: [['Routine cleaning', 'Recurring care for kitchens, bathrooms and everyday living spaces.'], ['Deep cleaning', 'A detailed refresh for spaces that need extra attention.'], ['Move-in / move-out', 'Prepare a property for its next chapter.']], audience: 'homes, offices and rental properties', detail: 'Share the size of your space, cleaning priorities and preferred frequency.', process: 'Discuss your space → Agree on a checklist → Choose a visit time', tip: 'Preparing for a cleaning visit', advice: 'Let your provider know about delicate surfaces, pets, access instructions and priority rooms.' },
  { id: 'handyman', label: 'Handyman', primary: '#b45309', tint: '#fffbeb', headline: ['Small projects. A better home.', 'Help with the home you love', 'Turn your to-do list into done', 'Practical upkeep for your properties', 'Tell us what needs fixing'], services: [['Repairs and maintenance', 'Address everyday wear, loose fittings and minor household repairs.'], ['Assembly and installation', 'Help with furniture, shelving and household fixtures.'], ['Finishing touches', 'Trim, patching and the details that bring a room together.']], audience: 'homeowners, landlords and property managers', detail: 'Send your project list, photos and any access or timing requirements.', process: 'Share your to-do list → Review the scope → Plan the visit', tip: 'Building a useful home repair list', advice: 'Group projects by room, include photos and note which items need attention first.' },
  { id: 'roofing', label: 'Roofing', primary: '#9f1239', tint: '#fff1f2', headline: ['A stronger roof starts with a clear plan', 'Care for the roof over your family', 'Your roof. Your next chapter.', 'Roofing support for your property portfolio', 'Start your roofing consultation'], services: [['Roof assessment', 'Discuss visible wear, leak concerns and the condition of your roof.'], ['Roof repairs', 'Target damaged areas with a scope based on an on-site assessment.'], ['Roof replacement', 'Explore materials, project stages and options for a new roof.']], audience: 'homeowners and commercial property teams', detail: 'Describe the roof type, signs of damage and your project goals.', process: 'Discuss your concerns → Assess the roof → Review your options', tip: 'Planning a roofing project', advice: 'Collect ground-level photos and note when leaks occur; leave roof access to an appropriately qualified professional.' },
  { id: 'landscaping', label: 'Landscaping', primary: '#3f6212', tint: '#f7fee7', headline: ['Bring your outdoor space to life', 'More to enjoy, right outside', 'Outdoor spaces with a sense of place', 'Grounds care for the places you manage', 'Plan your next outdoor project'], services: [['Lawn and garden care', 'Seasonal upkeep for lawns, beds and outdoor living areas.'], ['Landscape improvements', 'Explore planting, bed design and improvements to your outdoor space.'], ['Seasonal cleanups', 'Prepare your property for changing weather and growing seasons.']], audience: 'homes, communities and commercial properties', detail: 'Tell us about your property, growing conditions and the outdoor space you imagine.', process: 'Explore your space → Shape a plan → Schedule the work', tip: 'Preparing for a landscape consultation', advice: 'Bring property photos, sunlight observations and a list of how you want to use your outdoor space.' },
  { id: 'electrician', label: 'Electrician', primary: '#1d4ed8', tint: '#eff6ff', headline: ['Power your space with a clear plan', 'Thoughtful electrical care for your home', 'Lighting and power, reimagined', 'Electrical services for working spaces', 'Request an electrical consultation'], services: [['Troubleshooting', 'Arrange professional assessment of electrical concerns.'], ['Lighting and fixtures', 'Plan lighting updates and fixture installations for your space.'], ['Power upgrades', 'Discuss outlets, circuits and capacity requirements with your provider.']], audience: 'households, businesses and property managers', detail: 'Describe your project and current concerns; do not open panels or handle exposed wiring.', process: 'Describe the project → Arrange an assessment → Review the scope', tip: 'Planning an electrical upgrade', advice: 'List the equipment and spaces involved and discuss applicable permits with a qualified professional.' },
  { id: 'plumbing', label: 'Plumbing', primary: '#0369a1', tint: '#f0f9ff', headline: ['Keep your home flowing', 'Plumbing care for everyday living', 'Refresh the spaces you use every day', 'Plumbing support for busy properties', 'Tell us about your plumbing project'], services: [['Leak and fixture repairs', 'Address concerns with taps, toilets and visible plumbing fixtures.'], ['Drain concerns', 'Arrange an assessment of slow or troublesome drains.'], ['Fixture replacements', 'Plan practical updates for kitchens, bathrooms and utility spaces.']], audience: 'homes, rental properties and businesses', detail: 'Describe the affected fixture, when the issue began and any visible water damage.', process: 'Explain the issue → Review the situation → Agree on next steps', tip: 'Before your plumbing appointment', advice: 'Clear access to the affected area and note when the issue happens; avoid attempting unfamiliar repairs.' },
  { id: 'hvac', label: 'HVAC', primary: '#c2410c', tint: '#fff7ed', headline: ['Comfort starts with the right system', 'A more comfortable place to come home', 'Rethink your home comfort', 'Climate care for your working environment', 'Start your comfort consultation'], services: [['System maintenance', 'Discuss seasonal care for heating and cooling equipment.'], ['Heating and cooling repairs', 'Arrange an assessment when your system is not working as expected.'], ['System replacement', 'Explore equipment options suited to your property and needs.']], audience: 'homeowners, facilities teams and property managers', detail: 'Share your system type, symptoms and comfort goals.', process: 'Discuss your needs → Assess the system → Compare options', tip: 'Preparing for a comfort assessment', advice: 'Note equipment details, rooms with temperature differences and recent changes in system performance.' },
  { id: 'painting', label: 'Painting', primary: '#7e22ce', tint: '#faf5ff', headline: ['A new look for the spaces you love', 'Fresh color. A familiar feeling.', 'Make your next transformation memorable', 'Painting plans for commercial properties', 'Bring your painting ideas to us'], services: [['Interior painting', 'Refresh walls, ceilings and trim with a considered finish.'], ['Exterior painting', 'Plan preparation and coatings for your property exterior.'], ['Surface preparation', 'Discuss patching, preparation and finishing details before painting begins.']], audience: 'homeowners, businesses and property managers', detail: 'Share the rooms or surfaces, approximate dimensions and color ideas.', process: 'Explore your vision → Review surfaces → Plan preparation and painting', tip: 'Choosing a painting direction', advice: 'Compare color samples in your actual lighting and discuss surface condition and finish preferences.' },
  { id: 'pest-control', label: 'Pest Control', primary: '#166534', tint: '#f0fdf4', headline: ['A considered approach to pest concerns', 'Help protect the place you call home', 'A clearer plan for your property', 'Pest management for business spaces', 'Request a pest assessment'], services: [['Property inspection', 'Discuss pest activity and arrange an assessment of affected areas.'], ['Treatment planning', 'Review suitable treatment options and preparation requirements.'], ['Prevention and follow-up', 'Consider ongoing monitoring and steps to reduce future pest activity.']], audience: 'homes, rental properties and commercial spaces', detail: 'Describe what you have noticed, affected areas and any household considerations.', process: 'Share your observations → Assess the property → Review a treatment plan', tip: 'Preparing for a pest assessment', advice: 'Note where and when activity occurs and tell your provider about children, pets and other precautions.' }
];
export const serviceStyles = [
  { id: 'modern', label: 'Modern Essential', description: 'A spacious, service-first introduction with a clear project process.', layout: 'stack', spacing: 'roomy', font: 'sans', radius: 'soft', sections: ['Introduction', 'Services', 'Process', 'Get in touch'] },
  { id: 'neighborhood', label: 'Neighborhood', description: 'A welcoming, centered design focused on local service and personal care.', layout: 'center', spacing: 'roomy', font: 'serif', radius: 'round', sections: ['Welcome', 'Our approach', 'Services', 'Service area'] },
  { id: 'showcase', label: 'Project Journal', description: 'An editorial design for explaining your work and sharing project stories.', layout: 'stack', spacing: 'roomy', font: 'serif', radius: 'square', sections: ['Introduction', 'Project approach', 'Services', 'Project journal'] },
  { id: 'commercial', label: 'Commercial Pro', description: 'A dark, compact design built around scopes, planning and property teams.', layout: 'stack', spacing: 'compact', font: 'mono', radius: 'square', sections: ['Introduction', 'Capabilities', 'Coordination', 'Request scope'] },
  { id: 'booking', label: 'Service Request', description: 'A direct, request-first design with an editable visit request form.', layout: 'center', spacing: 'normal', font: 'sans', radius: 'round', sections: ['Introduction', 'Request a visit', 'What to share', 'Services'] }
];
export function serviceTemplateCatalog() {
  return serviceTrades.flatMap(trade => serviceStyles.map((style, index) => ({ id: `${trade.id}-${style.id}`, trade: trade.id, business: trade.label, name: `${trade.label} · ${style.label}`, description: style.description, headline: trade.headline[index], primary: style.id === 'commercial' ? '#93c5fd' : trade.primary, background: style.id === 'commercial' ? '#121c2b' : style.id === 'neighborhood' ? trade.tint : '#ffffff', foreground: style.id === 'commercial' ? '#f8fafc' : '#172033', font: style.font, layout: style.layout, sections: style.sections })));
}